[package]
name = "lp_tracker"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0.41"
chrono = "0.4.19"
clap = "3.0.0-beta.2"
csv = "1.1.6"
yahoo_finance_api = { version = "1.2.1", features = ['blocking'] }
serde = { version = "1", features = ["derive"] }
